### ISSUE TITLE
SibilantTutorial Export.csv - content query

### ISSUE THREAD

**Issue by JaneStuart-Smith** [MontrealCorpusTools/iscan-server#148]
I've just successfully completed the Sibilants tutorial  :-) (using google chrome on Windows)
When I opened up the SibilantsTutorial Export.csv, I found that the column 'utterance_label' is entirely empty, and 'syllable_stress' is mainly empty.  Is this right for this corpus?

**Comment by mmcauliffe** [comment]
Right, utterance label is not generally useful (it's constructed from the sound file and the beginning and end of the utterance).  I'll look into why it's empty, since that construction should happen every time the label is requested, but bottom line you can get the info from it in separate columns which is probably more useful.  

For the syllable stress, there's a known issue still open (https://github.com/mlml/unisyn_spade/issues/5) where the file generated has the incorrect number of syllables for many words, which leads to empty labels as there's a requirement of having the correct number of syllables to use it for encoding stress.

**Comment by mmcauliffe** [comment]
Ok, I've updated the tutorials to not reference utterance label, and syllable stress has been addressed by new csvs, closing this.
